baseurl = "https://kureta.xyz"
title = "Sahin Kureta - composer"
author = "Sahin Kureta"
canonifyurls = true
paginate = 10
theme = "hugo-swift-theme"
publishDir = "/home/kureta/srv/kureta.xyz"

[params]
brand = "kureta"
description = "A composer from Istanbul"
bgimg = "img/ignasi_pattern_s.png"

